In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

<h2>Define Hyper-parameters</h2>

In [2]:
num_iter = 10000 #training iterations
lr = 0.2

<h2>Define your input data and expected labels</h2>

In [3]:
# define input data and XOR gate outputs
x = np.array([[0,0], [0,1], [1, 0], [1,1]], np.float32)
y = np.array([[0], [1], [1] , [0]], np.float32) # one hot encode
#y = np.array([0, 1, 1, 0], np.float32)

<h2>Define placeholder and Variables</h2>

In [4]:
tf.reset_default_graph() # reset
# placeholders for feeding
X_in = tf.placeholder(tf.float32, shape=(4,2))
Y_hat = tf.placeholder(tf.float32, shape=(4,1))

# neural net vars
# hidden layer
w1 = tf.Variable(tf.random_normal(shape=[2,2]), tf.float32)
b1 = tf.Variable(tf.zeros([1,1]),tf.float32)

# output layer
wout = tf.Variable(tf.random_normal(shape=[2,1]), tf.float32)
bout = tf.Variable(tf.zeros([1,1]), tf.float32)

Instructions for updating:
Colocations handled automatically by placer.


<h2>Define the neural network</h2>

In [5]:
h_lay_out = tf.sigmoid(tf.add(tf.matmul(X_in, w1), b1)) # single hidden layer with sigmoid activation
output = tf.add(tf.matmul(h_lay_out, wout), bout) # output layer, scalar, sigmoid for classification

<h2>Define cost function</h2>

In [6]:
# cross entropy as cost
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=output,labels=Y_hat))

#define loss
optimizer = tf.train.GradientDescentOptimizer(learning_rate=lr)
train_op = optimizer.minimize(loss)

#compare the predicted labels with true labels (classification is round)
correct_pred = tf.equal(tf.round(tf.sigmoid(output)),Y_hat)

#compute the accuracy by taking average
accuracy = tf.reduce_mean(tf.cast(correct_pred,tf.float32),name='accuracy')

#Initialize the variables
init = tf.global_variables_initializer()

<h2>Execute training</h2>

In [7]:
with tf.Session() as sess:
    sess.run(init)

    for i in range(num_iter):
        sess.run(train_op, feed_dict={X_in: x, Y_hat: y})
        if i % 1000 == 0:
            print('Output')
            temp = sess.run(output,feed_dict={X_in: x, Y_hat: y})
            print(temp)
            print('Output sigmoid, which we use to classify')
            print(sess.run(tf.nn.sigmoid(temp)))
            print('True Labels')
            print(y)
            print('Loss')
            print(sess.run(loss, feed_dict={X_in: x, Y_hat: y}))
            print(sess.run(correct_pred, feed_dict={X_in: x, Y_hat: y}))
            acc = sess.run(accuracy,feed_dict={X_in: x, Y_hat: y})
            print("step "+str(i)+", Accuracy= {:.3f}".format(acc))

    print("Training finished!")
    

Output
[[0.15122736]
 [0.18721364]
 [0.0804329 ]
 [0.12171737]]
Output sigmoid, which we use to classify
[[0.5377349 ]
 [0.54666716]
 [0.5200974 ]
 [0.5303918 ]]
True Labels
[[0.]
 [1.]
 [1.]
 [0.]]
Loss
0.6962819
[[False]
 [ True]
 [ True]
 [False]]
step 0, Accuracy= 0.500
Output
[[-0.15178317]
 [ 0.06204645]
 [-0.01235799]
 [ 0.10407048]]
Output sigmoid, which we use to classify
[[0.4621269 ]
 [0.5155066 ]
 [0.49691054]
 [0.5259942 ]]
True Labels
[[0.]
 [1.]
 [1.]
 [0.]]
Loss
0.68215466
[[ True]
 [ True]
 [False]
 [False]]
step 1000, Accuracy= 0.500
Output
[[-1.7883623 ]
 [ 1.2145531 ]
 [ 0.08994558]
 [ 0.26877576]]
Output sigmoid, which we use to classify
[[0.14327362]
 [0.77110356]
 [0.52247125]
 [0.5667923 ]]
True Labels
[[0.]
 [1.]
 [1.]
 [0.]]
Loss
0.47507316
[[ True]
 [ True]
 [ True]
 [False]]
step 2000, Accuracy= 0.750
Output
[[-2.8474123]
 [ 1.9219556]
 [ 1.9276843]
 [-1.0845265]]
Output sigmoid, which we use to classify
[[0.0548152 ]
 [0.8723563 ]
 [0.87299293]
 [0.25265038

<h2>Plot</h2>